version: 0.2

env:
  variables:
    ANDROID_HOME: /usr/lib/android-sdk

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - mkdir -p $ANDROID_HOME
      - wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
      - unzip commandlinetools-linux-*.zip
      - mkdir -p $ANDROID_HOME/cmdline-tools/latest
      - mv cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest
      - yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
      - $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

  build:
    commands:
      - chmod +x gradlew
      - ./gradlew assembleDebug

artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
